### ISSUE TITLE
[Webschool.io - Be MEAN - MongoDB - Aula 01] - URL do exercício dando 404

### ISSUE THREAD

**Issue by renatogalvones** [Webschool-io/be-mean-instagram-mongodb-excercises#1121]
Não estou conseguindo encontrar no repositório esse primeiro exercício.

![screen shot 2016-02-12 at 2 41 50 pm](https://cloud.githubusercontent.com/assets/302819/13013791/3171d342-d198-11e5-91ed-49931319fca4.png)

**Comment by wbruno** [comment]
Foi criado um novo repositório para um eBook. Está neste endereço aqui agora:

https://github.com/Webschool-io/MongoDb-ebook/blob/6e4007d73d5b25b7218ef0b9c4f8eb700bb5f104/pt-br/export_import.md

**Comment by renatogalvones** [comment]
Show!

Se der, deixa como uma annotation no video. =]

Valeu!

**Comment by suissa** [comment]
No video não tem mais como fazer mas rola colcoar na descrição

**Comment by DouglasHennrich** [comment]
coloca aquelas anotação em cima do video
