### ISSUE TITLE
Corrigir o 'excercises' para 'exercises' no título do repositório

### ISSUE THREAD

**Issue by marcosdiasdev** [Webschool-io/be-mean-instagram-mongodb-excercises#968]
Fala, mestre. Se for possível e achar interessante, remova aquele 'c' que está sobrando no 'exercises' do título do repositório. Acabei de me atrapalhar aqui por causa dele :smile: 
Peço desculpas se usei o local errado.
Abraço.

**Comment by DouglasHennrich** [comment]
Acho que não da para trocar o título do repositório depois que ele é criado =/

**Comment by marcosdiasdev** [comment]
Creio que dá, @DouglasHennrich. É a primeira opção lá nas settings do repositório .

**Comment by DouglasHennrich** [comment]
:+1:
